modLoader="javafml"
loaderVersion="[1,)"
license="gpl"

[[mods]] #mandatory
modId="multiworld"
version="1.21.10"
displayName="Multiworld"
authors="isaiah"
description="This is an example description! Tell everyone what your mod is about!"
#logoFile=""

[[dependencies.multiworld]]
    modId="neoforge"
    type="required"
    versionRange="[21.2.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.multiworld]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.9,)"
    ordering="NONE"
    side="BOTH"

[[mixins]]
    config="fantasy.mixins.json"

[[mixins]]
    config="multiworld.mixins.json"